name: PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
    - name: install
      run: yarn install --immutable
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
