name: PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Enable Corepack
      run: corepack enable
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: 23.x
    - name: install
      uses: borales/actions-yarn@v5
      with:
        cmd: install
    - name: lint
      uses: borales/actions-yarn@v5
      with:
        cmd: lint
    - name: build
      uses: borales/actions-yarn@v5
      with:
        cmd: build
